### ISSUE TITLE
provide slides in other format than keynote

### ISSUE THREAD

**Issue by fmichonneau** [Reproducible-Science-Curriculum/rr-publication#2]
@kcranston could you please provide the slideshow in PDF? I'm working on the post-workshop survey and I'd like to make sure I match the questions to what is covered by the slides but I can't open keynote files. Thanks!

**Comment by hlapp** [comment]
They are also linked [in HTML format](http://reproducible-science-curriculum.github.io/2015-05-14-reproducible-science-duke/publication-slides/assets/player/KeynoteDHTMLPlayer.html#0) from the Duke workshop website.

**Comment by hlapp** [comment]
@fmichonneau I think the conversion to Reveal/markdown/HTML as per #3 addresses this. Reopen if not.
